name: Deploy Medusa Application

on:
  push:
    branches:
      - master

permissions:
  id-token: write  # Add this permission
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  
          aws-region: ${{ secrets.AWS_REGION }} 
          audience: sts.amazonaws.com        

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t medusa-app:latest .  # Use a descriptive name

      - name: Tag Docker image
        run: |
          docker tag medusa-app:latest ${{ steps.ecr-login.outputs.registry }}/medusa-app:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.ecr-login.outputs.registry }}/medusa-app:latest

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5  # Change to your desired version

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Apply
        run: terraform apply  -auto-approve 
        
      - name: Deploy to ECS
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLUSTER_NAME: my-ecs-cluster
          SERVICE_NAME: my-service
          TASK_DEFINITION: medusa-task

        run: |
          # Register a new revision of the task definition
          NEW_TASK_DEFINITION=$(aws ecs register-task-definition \
            --family $TASK_DEFINITION \
            --container-definitions "[{\"name\":\"medusa\",\"image\":\"895992122733.dkr.ecr.us-east-1.amazonaws.com/medusa-app:latest\",\"memory\":\"512\",\"cpu\":\"256\",\"essential\":true}]" \
            --query 'taskDefinition.taskDefinitionArn' --output text)

          # Update the ECS service to use the new task definition
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $NEW_TASK_DEFINITION